# Makefile

# defaults
SOURCES=../hdl
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

#Add your sources one by one as below or use *.v to add all verilog files
VERILOG_SOURCES += $(wildcard $(SOURCES)/*.v)
# VERILOG_SOURCES += $(SOURCES)/ALU.v

# add sources ending in .v with wildcard * 







# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file
#Should be the name of the basic computer module for you
TOPLEVEL = BC_I

# MODULE is the basename of the Python test file
#Name of your python file
MODULE = cocotb_bc1_test

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim
